Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  #config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.forward_agent = true
  config.vm.network "forwarded_port", guest: 80, host: 8089
  config.vm.network :public_network, ip: "192.168.56.1"
  config.vm.provision "shell", inline: "echo Hello, World >> hello.txt"
end
